#!/bin/sh
#
# AUTHOR: manisk 
# DATE: Sat Nov 07 2009
# DESC: Elvi to search Amazon India
# elvis: amazonin -- Search Amazon India (www.amazon.in)

. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Amazon India (www.amazon.in)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
    w3_browse_url "https://www.amazon.in/"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "https://www.amazon.in/s?k=${escaped_args}"
fi
